[[apps]]
  name = "MADS"
  weight = 10
  identifier = "mads"
  url = "/apps/mads/"

[[apps]]
  name = "Role Manager"
  weight = 20
  identifier = "role-manager"
  url = "/apps/role-manager/"

[[apps]]
  name = "Entity Manager"
  weight = 30
  identifier = "entity-manager"
  url = "/apps/entity-manager/"

[[apps]]
  name = "IoT Manager"
  weight = 40
  identifier = "iot-manager"
  url = "/apps/iot-manager/"

[[apps]]
  name = "Dashboards"
  weight = 50
  identifier = "dashboards"
  url = "/apps/dashboards/"

[[apps]]
  name = "Widget Manager"
  weight = 60
  identifier = "widget-manager"
  url = "/apps/widget-manager/"

[[apps]]
  name = "Data Insights"
  weight = 70
  identifier = "data-insights"
  url = "/apps/data-insights/"

[[apps]]
  name = "Data Cruncher"
  weight = 80
  identifier = "data-cruncher"
  url = "/apps/data-cruncher/"

[[apps]]
  name = "Alerts"
  weight = 90
  identifier = "alerts"
  url = "/apps/alerts/"

[[apps]]
  name = "Digital Twin"
  weight = 100
  identifier = "digital-twin"
  url = "/apps/digital-twin/"

[[apps]]
  name = "Prologue"
  weight = 210
  identifier = "prologue"
  url = "/apps/prologue/"

[[apps]]
  name = "Help"
  weight = 220
  identifier = "help"
  url = "/apps/help/"



[[showcase]]
  name = "Case Studies"
  weight = 10
  identifier = "case-studies"
  url = "/showcase/case-studies/"

[[showcase]]
  name = "MADS Solutions"
  weight = 20
  identifier = "solutions"
  url = "/showcase/solutions/"



[[main]]
  name = "Apps"
  url = "/apps/mads/what-is-iot/"
  weight = 10

[[main]]
  name = "Tutorial"
  url = "/tutorial/introduction/"
  weight = 20

[[main]]
  name = "Showcase"
  url = "/showcase/manufacturing/"
  weight = 30

[[main]]
  name = "Blog"
  url = "/blog/"
  weight = 40

# [[main]]
#   name = "Community"
#   url = "https://github.com/h-enk/doks/discussions"
#   weight = 50

[[social]]
   name = "Twitter"
   pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-twitter\"><path d=\"M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z\"></path></svg>"
   url = "https://twitter.com/datakrew"
   weight = 10

[[social]]
  name = "GitHub"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-github\"><path d=\"M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22\"></path></svg>"
  url = "https://github.com/DataKrewTech/MADS-IoT-Explorer"
  post = "v0.1.0"
  weight = 20

[[footer]]
   name = "Contact Us"
   url = "https://datakrew.com/contact.html"
   weight = 10

# [[footer]]
#   name = "Privacy"
#   url = "/privacy-policy/"
#   weight = 20