# Meta Data for SEO

## Homepage
title = "MADS"
titleSeparator = "-"
titleAddition = "IoT Platform"
description = "100% self-service, no-code, intuitive IoT platform for 500x rapid implementation of enterprise IoT projects."

## Open Graph + Twitter Cards
images = ["mads-card-1280x638.png"]
twitterSite = "datakrew"
twitterCreator = "datakrew"
facebookAuthor = "datakrewtech"
facebookPublisher = "datakrewtech"
ogLocale = "en_US"

## JSON-LD
schemaType = "Organization"
schemaLogo = "mads-square-logo.png"
schemaTwitter = "https://twitter.com/datakrew"
schemaLinkedIn = "https://linkedin.com/company/datakrew"
schemaGitHub = "https://github.com/datakrewtech"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Powered by <a href=\"https://www.netlify.com/\">Netlify</a>, <a href=\"https://gohugo.io/\">Hugo</a>, and <a href=\"https://getdoks.org/\">Doks</a>"

# Alert
alert = true
alertText = "Like MADS? <a class=\"alert-link\" style=\"color:#fcf003;\" href=\"https://github.com/DataKrewTech/MADS-IoT-Explorer\">Star on GitHub</a>!</a>"

# Edit Page
docsRepo = "https://github.com/DataKrewTech/MADS-Docs"
editPage = false
